export type MilestoneTier = "bronze" | "silver" | "gold" | "platinum" | "diamond";

export interface MilestoneDef {
  threshold: number;
  name: string;
  emoji: string;
  tier: MilestoneTier;
  colorFrom: string;
  colorTo: string;
  description: string;
  animationClass?: string;
}

export const MILESTONE_THRESHOLDS: number[] = Array.from({ length: 50 }, (_, i) => (i + 1) * 1000);

export const MILESTONES: MilestoneDef[] = [
  // ── Bronze (1K–5K) ──────────────────────────────────────────────────────────
  {
    threshold: 1000,
    name: "First Step",
    emoji: "🪙",
    tier: "bronze",
    colorFrom: "#92400e",
    colorTo: "#b45309",
    description: "Earned your first 1,000 coins. The journey begins!",
  },
  {
    threshold: 2000,
    name: "Coin Collector",
    emoji: "💰",
    tier: "bronze",
    colorFrom: "#78350f",
    colorTo: "#d97706",
    description: "2,000 coins in the bank. You're getting the hang of it!",
  },
  {
    threshold: 3000,
    name: "Quiz Enthusiast",
    emoji: "📚",
    tier: "bronze",
    colorFrom: "#92400e",
    colorTo: "#f59e0b",
    description: "3,000 coins earned — a true quiz enthusiast.",
  },
  {
    threshold: 4000,
    name: "Copper Crown",
    emoji: "🏅",
    tier: "bronze",
    colorFrom: "#7c2d12",
    colorTo: "#ea580c",
    description: "4,000 coins. The copper crown is yours!",
  },
  {
    threshold: 5000,
    name: "Bronze Champion",
    emoji: "🥉",
    tier: "bronze",
    colorFrom: "#92400e",
    colorTo: "#c2410c",
    description: "5,000 coins! You've mastered the bronze tier.",
  },

  // ── Silver (6K–10K) ─────────────────────────────────────────────────────────
  {
    threshold: 6000,
    name: "Silver Spark",
    emoji: "⚡",
    tier: "silver",
    colorFrom: "#334155",
    colorTo: "#64748b",
    description: "6,000 coins — the silver era has begun.",
  },
  {
    threshold: 7000,
    name: "Steel Resolve",
    emoji: "🛡️",
    tier: "silver",
    colorFrom: "#1e293b",
    colorTo: "#475569",
    description: "7,000 coins of pure determination.",
  },
  {
    threshold: 8000,
    name: "Moonbeam",
    emoji: "🌙",
    tier: "silver",
    colorFrom: "#1e3a5f",
    colorTo: "#94a3b8",
    description: "8,000 coins bright as the moon.",
  },
  {
    threshold: 9000,
    name: "Quicksilver",
    emoji: "💨",
    tier: "silver",
    colorFrom: "#0f172a",
    colorTo: "#64748b",
    description: "9,000 coins — moving at quicksilver speed!",
  },
  {
    threshold: 10000,
    name: "Silver Legend",
    emoji: "🥈",
    tier: "silver",
    colorFrom: "#1e293b",
    colorTo: "#cbd5e1",
    description: "10,000 coins! A true silver legend.",
  },

  // ── Gold (11K–20K) ──────────────────────────────────────────────────────────
  {
    threshold: 11000,
    name: "Golden Touch",
    emoji: "✨",
    tier: "gold",
    colorFrom: "#713f12",
    colorTo: "#ca8a04",
    description: "11,000 coins — everything you touch turns to gold.",
    animationClass: "legendary-card",
  },
  {
    threshold: 12000,
    name: "Sun Seeker",
    emoji: "☀️",
    tier: "gold",
    colorFrom: "#78350f",
    colorTo: "#eab308",
    description: "12,000 coins blazing like the sun.",
    animationClass: "legendary-card",
  },
  {
    threshold: 13000,
    name: "Golden Streak",
    emoji: "🔥",
    tier: "gold",
    colorFrom: "#92400e",
    colorTo: "#f59e0b",
    description: "13,000 coins on a golden streak.",
    animationClass: "legendary-card",
  },
  {
    threshold: 14000,
    name: "Gilded Mind",
    emoji: "🧠",
    tier: "gold",
    colorFrom: "#713f12",
    colorTo: "#fbbf24",
    description: "14,000 coins — a gilded mind at work.",
    animationClass: "legendary-card",
  },
  {
    threshold: 15000,
    name: "Fortune Seeker",
    emoji: "🍀",
    tier: "gold",
    colorFrom: "#78350f",
    colorTo: "#facc15",
    description: "15,000 coins. Fortune favours the persistent!",
    animationClass: "legendary-card",
  },
  {
    threshold: 16000,
    name: "Gold Rush",
    emoji: "⛏️",
    tier: "gold",
    colorFrom: "#92400e",
    colorTo: "#eab308",
    description: "16,000 coins mined from sheer effort.",
    animationClass: "legendary-card",
  },
  {
    threshold: 17000,
    name: "Aureus",
    emoji: "🏛️",
    tier: "gold",
    colorFrom: "#713f12",
    colorTo: "#f59e0b",
    description: "17,000 coins — worthy of ancient gold coins.",
    animationClass: "legendary-card",
  },
  {
    threshold: 18000,
    name: "Midas Mark",
    emoji: "👑",
    tier: "gold",
    colorFrom: "#7c2d12",
    colorTo: "#fbbf24",
    description: "18,000 coins. The Midas mark is earned.",
    animationClass: "legendary-card",
  },
  {
    threshold: 19000,
    name: "Solar Flare",
    emoji: "🌟",
    tier: "gold",
    colorFrom: "#92400e",
    colorTo: "#fde047",
    description: "19,000 coins — a solar flare of achievement.",
    animationClass: "legendary-card",
  },
  {
    threshold: 20000,
    name: "Gold Master",
    emoji: "🥇",
    tier: "gold",
    colorFrom: "#78350f",
    colorTo: "#facc15",
    description: "20,000 coins! You've achieved Gold Mastery.",
    animationClass: "legendary-card",
  },

  // ── Platinum (21K–35K) ──────────────────────────────────────────────────────
  {
    threshold: 21000,
    name: "Ice Breaker",
    emoji: "🧊",
    tier: "platinum",
    colorFrom: "#164e63",
    colorTo: "#06b6d4",
    description: "21,000 coins — breaking into platinum territory.",
  },
  {
    threshold: 22000,
    name: "Tidal Force",
    emoji: "🌊",
    tier: "platinum",
    colorFrom: "#0c4a6e",
    colorTo: "#0891b2",
    description: "22,000 coins with the force of the tide.",
  },
  {
    threshold: 23000,
    name: "Arctic Star",
    emoji: "❄️",
    tier: "platinum",
    colorFrom: "#0f172a",
    colorTo: "#22d3ee",
    description: "23,000 coins, cold and brilliant as an arctic star.",
  },
  {
    threshold: 24000,
    name: "Cyber Sage",
    emoji: "🤖",
    tier: "platinum",
    colorFrom: "#164e63",
    colorTo: "#67e8f9",
    description: "24,000 coins — the wisdom of a cyber sage.",
  },
  {
    threshold: 25000,
    name: "Quarter Century",
    emoji: "🔵",
    tier: "platinum",
    colorFrom: "#0c4a6e",
    colorTo: "#38bdf8",
    description: "25,000 coins! A quarter century of earning.",
  },
  {
    threshold: 26000,
    name: "Crystal Clear",
    emoji: "💎",
    tier: "platinum",
    colorFrom: "#0f172a",
    colorTo: "#7dd3fc",
    description: "26,000 coins — crystal clear brilliance.",
  },
  {
    threshold: 27000,
    name: "Deep Diver",
    emoji: "🐋",
    tier: "platinum",
    colorFrom: "#1e3a5f",
    colorTo: "#0ea5e9",
    description: "27,000 coins. You dive deeper than anyone.",
  },
  {
    threshold: 28000,
    name: "Glacier Peak",
    emoji: "🏔️",
    tier: "platinum",
    colorFrom: "#0c4a6e",
    colorTo: "#22d3ee",
    description: "28,000 coins atop the glacier peak.",
  },
  {
    threshold: 29000,
    name: "Prism Elite",
    emoji: "🔷",
    tier: "platinum",
    colorFrom: "#164e63",
    colorTo: "#38bdf8",
    description: "29,000 coins — the prism elite.",
  },
  {
    threshold: 30000,
    name: "Platinum Prestige",
    emoji: "🌐",
    tier: "platinum",
    colorFrom: "#0f172a",
    colorTo: "#7dd3fc",
    description: "30,000 coins! Platinum Prestige achieved.",
  },
  {
    threshold: 31000,
    name: "Frost Titan",
    emoji: "🧊",
    tier: "platinum",
    colorFrom: "#0c4a6e",
    colorTo: "#06b6d4",
    description: "31,000 coins — a titan of frost and wisdom.",
  },
  {
    threshold: 32000,
    name: "Sapphire Soul",
    emoji: "💠",
    tier: "platinum",
    colorFrom: "#1e3a5f",
    colorTo: "#0891b2",
    description: "32,000 coins with the soul of a sapphire.",
  },
  {
    threshold: 33000,
    name: "Tempest",
    emoji: "🌪️",
    tier: "platinum",
    colorFrom: "#164e63",
    colorTo: "#22d3ee",
    description: "33,000 coins — an unstoppable tempest.",
  },
  {
    threshold: 34000,
    name: "Aether Knight",
    emoji: "⚔️",
    tier: "platinum",
    colorFrom: "#0f172a",
    colorTo: "#67e8f9",
    description: "34,000 coins. The aether knight rises.",
  },
  {
    threshold: 35000,
    name: "Platinum Sovereign",
    emoji: "🏆",
    tier: "platinum",
    colorFrom: "#0c4a6e",
    colorTo: "#38bdf8",
    description: "35,000 coins! The Platinum Sovereign reigns.",
  },

  // ── Diamond (36K–50K) ───────────────────────────────────────────────────────
  {
    threshold: 36000,
    name: "Starborn",
    emoji: "🌠",
    tier: "diamond",
    colorFrom: "#3b0764",
    colorTo: "#7c3aed",
    description: "36,000 coins — born of stardust and brilliance.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 37000,
    name: "Nebula Walker",
    emoji: "🌌",
    tier: "diamond",
    colorFrom: "#2e1065",
    colorTo: "#6d28d9",
    description: "37,000 coins walking through nebulae.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 38000,
    name: "Void Breaker",
    emoji: "🌑",
    tier: "diamond",
    colorFrom: "#1e1b4b",
    colorTo: "#7c3aed",
    description: "38,000 coins breaking through the void.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 39000,
    name: "Aurora",
    emoji: "🌈",
    tier: "diamond",
    colorFrom: "#3b0764",
    colorTo: "#a855f7",
    description: "39,000 coins — radiant as the aurora borealis.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 40000,
    name: "Cosmic Forty",
    emoji: "🚀",
    tier: "diamond",
    colorFrom: "#2e1065",
    colorTo: "#c026d3",
    description: "40,000 coins! A cosmic milestone achieved.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 41000,
    name: "Prism Lord",
    emoji: "💜",
    tier: "diamond",
    colorFrom: "#1e1b4b",
    colorTo: "#8b5cf6",
    description: "41,000 coins — the Prism Lord commands.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 42000,
    name: "Galaxy Brain",
    emoji: "🧬",
    tier: "diamond",
    colorFrom: "#3b0764",
    colorTo: "#d946ef",
    description: "42,000 coins of galaxy-level thinking.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 43000,
    name: "Supernova",
    emoji: "💥",
    tier: "diamond",
    colorFrom: "#2e1065",
    colorTo: "#a855f7",
    description: "43,000 coins — a supernova of achievement.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 44000,
    name: "Eternal Flame",
    emoji: "🔮",
    tier: "diamond",
    colorFrom: "#1e1b4b",
    colorTo: "#c026d3",
    description: "44,000 coins, burning eternally bright.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 45000,
    name: "Celestial",
    emoji: "✨",
    tier: "diamond",
    colorFrom: "#3b0764",
    colorTo: "#7c3aed",
    description: "45,000 coins — celestial power unlocked.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 46000,
    name: "Arcane Ascendant",
    emoji: "🌀",
    tier: "diamond",
    colorFrom: "#2e1065",
    colorTo: "#8b5cf6",
    description: "46,000 coins. Arcane ascendance achieved.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 47000,
    name: "Infinite Spark",
    emoji: "⚡",
    tier: "diamond",
    colorFrom: "#1e1b4b",
    colorTo: "#d946ef",
    description: "47,000 coins — infinite spark, infinite potential.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 48000,
    name: "Transcendent",
    emoji: "🦋",
    tier: "diamond",
    colorFrom: "#3b0764",
    colorTo: "#a855f7",
    description: "48,000 coins. You have transcended the ordinary.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 49000,
    name: "Diamond Overlord",
    emoji: "👾",
    tier: "diamond",
    colorFrom: "#2e1065",
    colorTo: "#c026d3",
    description: "49,000 coins — overlord of the diamond realm.",
    animationClass: "rainbow-card",
  },
  {
    threshold: 50000,
    name: "BittsQuiz Legend",
    emoji: "🏆",
    tier: "diamond",
    colorFrom: "#1e1b4b",
    colorTo: "#7c3aed",
    description: "50,000 coins! The ultimate BittsQuiz Legend.",
    animationClass: "rainbow-card",
  },
];

export function getMilestoneByThreshold(threshold: number): MilestoneDef {
  return MILESTONES.find((m) => m.threshold === threshold) ?? MILESTONES[0];
}

export const TIER_COLORS: Record<MilestoneTier, { border: string; label: string; text: string }> = {
  bronze:   { border: "border-amber-600",   label: "Bronze",   text: "text-amber-500"  },
  silver:   { border: "border-slate-400",   label: "Silver",   text: "text-slate-300"  },
  gold:     { border: "border-yellow-400",  label: "Gold",     text: "text-yellow-400" },
  platinum: { border: "border-cyan-400",    label: "Platinum", text: "text-cyan-400"   },
  diamond:  { border: "border-purple-400",  label: "Diamond",  text: "text-purple-400" },
};
