export type PackDef = {
  name: string;
  description: string;
  cost: number;
  slug: string;
  icon: string;
  colorFrom: string;
  colorTo: string;
  isFestival: boolean;
  festivalDate?: string;
  isActive: boolean;
};

export const PACKS_DATA: PackDef[] = [
  {
    name: "Tech Pack",
    description: "Discover digital creatures born from code and circuits.",
    cost: 100,
    slug: "tech-pack",
    icon: "💻",
    colorFrom: "#0f172a",
    colorTo: "#1e3a5f",
    isFestival: false,
    isActive: true,
  },
  {
    name: "Sports Pack",
    description: "Collect legendary athletes and sporting spirits.",
    cost: 80,
    slug: "sports-pack",
    icon: "⚽",
    colorFrom: "#052e16",
    colorTo: "#14532d",
    isFestival: false,
    isActive: true,
  },
  {
    name: "Magic Pack",
    description: "Uncover mystical beings from the wizarding world.",
    cost: 120,
    slug: "magic-pack",
    icon: "⚡",
    colorFrom: "#1e1b4b",
    colorTo: "#3730a3",
    isFestival: false,
    isActive: true,
  },
  {
    name: "Hero Pack",
    description: "Assemble earth's mightiest collectible quizlets.",
    cost: 150,
    slug: "hero-pack",
    icon: "🦸",
    colorFrom: "#450a0a",
    colorTo: "#991b1b",
    isFestival: false,
    isActive: true,
  },
  {
    name: "Music Pack",
    description: "Collect the spirits of art, music, and creativity.",
    cost: 90,
    slug: "music-pack",
    icon: "🎵",
    colorFrom: "#4a044e",
    colorTo: "#86198f",
    isFestival: false,
    isActive: true,
  },
  {
    name: "Science Pack",
    description: "Discover beings made from atoms, equations, and cosmos.",
    cost: 110,
    slug: "science-pack",
    icon: "🔬",
    colorFrom: "#082f49",
    colorTo: "#0369a1",
    isFestival: false,
    isActive: true,
  },
  {
    name: "Rainbow Pack",
    description: "The rarest pack. Contains beings from all realms — and one impossible legend.",
    cost: 500,
    slug: "rainbow-pack",
    icon: "🌈",
    colorFrom: "#1f2937",
    colorTo: "#4f46e5",
    isFestival: false,
    isActive: true,
  },
  // Festival packs
  {
    name: "New Year Bash",
    description: "Ring in the new year with exclusive festive quizlets!",
    cost: 200,
    slug: "newyear-pack",
    icon: "🎆",
    colorFrom: "#1c1917",
    colorTo: "#292524",
    isFestival: true,
    festivalDate: "01-01",
    isActive: false,
  },
  {
    name: "Valentine's Pack",
    description: "Love is in the air — and in these exclusive quizlets.",
    cost: 180,
    slug: "love-pack",
    icon: "❤️",
    colorFrom: "#4c0519",
    colorTo: "#9f1239",
    isFestival: true,
    festivalDate: "02-14",
    isActive: false,
  },
  {
    name: "Holi Splash",
    description: "Colour-soaked quizlets from the festival of colours!",
    cost: 160,
    slug: "holi-pack",
    icon: "🌈",
    colorFrom: "#4a044e",
    colorTo: "#7e22ce",
    isFestival: true,
    festivalDate: "03-25",
    isActive: false,
  },
  {
    name: "Halloween Haunt",
    description: "Spooky spirits that only emerge on the scariest night.",
    cost: 220,
    slug: "spooky-pack",
    icon: "🎃",
    colorFrom: "#1c0a00",
    colorTo: "#431407",
    isFestival: true,
    festivalDate: "10-31",
    isActive: false,
  },
  {
    name: "Diwali Glow",
    description: "Illuminate your collection with festival of lights quizlets.",
    cost: 175,
    slug: "diwali-pack",
    icon: "🪔",
    colorFrom: "#422006",
    colorTo: "#78350f",
    isFestival: true,
    festivalDate: "11-01",
    isActive: false,
  },
  {
    name: "Christmas Magic",
    description: "Collect the magic of the most wonderful time of the year.",
    cost: 250,
    slug: "xmas-pack",
    icon: "🎄",
    colorFrom: "#052e16",
    colorTo: "#166534",
    isFestival: true,
    festivalDate: "12-25",
    isActive: false,
  },
];
